// <auto-generated />
using System;
using EF_04_PhieuThu.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_04_PhieuThu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230712094906_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_04_PhieuThu.Models.ChiTietPhieuThu", b =>
                {
                    b.Property<int>("ChiTietPhieuThuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietPhieuThuId"));

                    b.Property<int>("NguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int>("PhieuThuId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.HasKey("ChiTietPhieuThuId");

                    b.HasIndex("NguyenLieuId");

                    b.HasIndex("PhieuThuId");

                    b.ToTable("ChiTietPhieuThu");
                });

            modelBuilder.Entity("EF_04_PhieuThu.Models.LoaiNguyenLieu", b =>
                {
                    b.Property<int>("LoaiNguyenLieuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiNguyenLieuId"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoaiNguyenLieuId");

                    b.ToTable("LoaiNguyenLieu");
                });

            modelBuilder.Entity("EF_04_PhieuThu.Models.NguyenLieu", b =>
                {
                    b.Property<int>("NguyenLieuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguyenLieuId"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiaBan")
                        .HasColumnType("int");

                    b.Property<int>("LoaiNguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongKho")
                        .HasColumnType("int");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguyenLieuId");

                    b.HasIndex("LoaiNguyenLieuId");

                    b.ToTable("NguyenLieu");
                });

            modelBuilder.Entity("EF_04_PhieuThu.Models.PhieuThu", b =>
                {
                    b.Property<int>("PhieuThuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhieuThuId"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienLap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThanhTien")
                        .HasColumnType("int");

                    b.HasKey("PhieuThuId");

                    b.ToTable("PhieuThu");
                });

            modelBuilder.Entity("EF_04_PhieuThu.Models.ChiTietPhieuThu", b =>
                {
                    b.HasOne("EF_04_PhieuThu.Models.NguyenLieu", "NguyenLieu")
                        .WithMany()
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_04_PhieuThu.Models.PhieuThu", "PhieuThu")
                        .WithMany("ListChiTietPhieuThu")
                        .HasForeignKey("PhieuThuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("PhieuThu");
                });

            modelBuilder.Entity("EF_04_PhieuThu.Models.NguyenLieu", b =>
                {
                    b.HasOne("EF_04_PhieuThu.Models.LoaiNguyenLieu", "LoaiNguyenLieu")
                        .WithMany("ListNguyenLieu")
                        .HasForeignKey("LoaiNguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiNguyenLieu");
                });

            modelBuilder.Entity("EF_04_PhieuThu.Models.LoaiNguyenLieu", b =>
                {
                    b.Navigation("ListNguyenLieu");
                });

            modelBuilder.Entity("EF_04_PhieuThu.Models.PhieuThu", b =>
                {
                    b.Navigation("ListChiTietPhieuThu");
                });
#pragma warning restore 612, 618
        }
    }
}
